matrix:
  include:
    - language: cpp
      sudo: required
      services:
        - docker
      cache:
        - ccache
      before_install:
        - docker pull pinterestbo/rocksplicator-build:rocksdb5.7.2
      script:
        - cd $HOME/.ccache
        - |
          if [[ -f touch_order.txt ]]; then
            while read fn; do
              touch $fn
            done < touch_order.txt
            # touch changed git files to trigger their rebuild
            read PREVIOUS_GIT_COMMIT < previous_git_commit.txt
            changed_files=`git diff --name-only $PREVIOUS_GIT_COMMIT HEAD`
            echo "Previously cached Travis build based on git commit ${PREVIOUS_GIT_COMMIT}."
            echo "... changed files since then:"
            echo $changed_files
            cd "${TRAVIS_BUILD_DIR}"
            touch `echo $changed_files`
            echo "Touch done"
          else
            echo "Full build ..."
          fi
        - docker run -v $HOME/.ccache:/rocksplicator/build -v $TRAVIS_BUILD_DIR:/rocksplicator pinterestbo/rocksplicator-build:rocksdb5.7.2 /bin/sh -c "cd /rocksplicator/build && cmake .. && make && env CTEST_OUTPUT_ON_FAILURE=1 make test"
      before_cache:
        - cd $HOME/.ccache && find . -type f -printf "%T+\t%p\n" | sort | cut -f 2 > touch_order.txt
        - cd "${TRAVIS_BUILD_DIR}" && git rev-parse HEAD > $HOME/.ccache/previous_git_commit.txt

    - language: java
      sudo: required
      dist: trusty
      group: edge
      jdk: oraclejdk8
      cache:
        directories:
          - $HOME/.m2
      notifications:
          email: false
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -q -y --force-yes libboost-dev libboost-test-dev libboost-program-options-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev
        - wget http://archive.apache.org/dist/thrift/0.9.1/thrift-0.9.1.tar.gz
        - tar xfz thrift-0.9.1.tar.gz
        - cd thrift-0.9.1 && ./configure --with-cpp=no --with-c_glib=no --with-java=yes --with-python=no --with-ruby=no --with-erlang=no --with-go=no --with-nodejs=no --with-php=no && sudo make install
      script:
        - cd ../controller; mvn clean package -DskipTests # if you want to test:  mvn "-DfailIfNoTests=false" test
